### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by dddExperiments** [antelle/node-stream-zip#14]
When running:
`node server.js 21154fcf-1677-4a94-8ae4-587d42164d15.zip`

I got the following output:
```
Opening zip: 21154fcf-1677-4a94-8ae4-587d42164d15.zip
buffer.js:816
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:816:11)
    at Buffer.readUInt32LE (buffer.js:878:5)
    at FsRead.readUntilFoundCallback [as callback] (D:\output\node_modules\node-stream-zip\node_stream_zip.js:190:28)
    at FsRead.readCallback (D:\output\node_modules\node-stream-zip\node_stream_zip.js:800:21)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:681:17)
```

Server.js file:
```
"use strict";

var StreamZip = require('node-stream-zip');

var args = process.argv.slice(2);

if (args.length !== 1) {
	console.log("you need to provide a zip file.");
}
else {
	console.log("Opening zip: " + args[0]);
	var zip = new StreamZip({
		file: args[0],
		storeEntries: true
	});
	zip.on('error', function(err) { console.log(err); });
	zip.on('ready', function() {
		console.log("Ready");
		console.log('Entries read: ' + zip.entriesCount);
		var data = zip.entryDataSync('properties.json');
	});
}
```

The zip file is big (~1.26GB) and contains ~35k files -> close to half of 65k limit?
I've posted the file on [WeTransfer](https://www.wetransfer.com/downloads/5a62e8e97922f31040f752798d0c4bbd20170103064251/c2afbb0949fc2a960dc892819335caaf20170103064251/abbec0) (link will be valid for one week).
The archive has been generated with [zip-folder.js](https://github.com/dddExperiments/PhotosynthDownloader/blob/master/zip-folder.js).

Thanks for your work: node-stream-zip is very useful to me!

**Comment by antelle** [comment]
Thanks! Fixed, added a test.
Your archive contains a special comment...

**Comment by dddExperiments** [comment]
It's working: thanks a lot for the speedy fix!

**Comment by edtechd** [comment]
I am not sure that the fix is correct. For example, when trying to explore this small file http://www.edtech.ru/dev/test2.zip, I get an error "Bar archive" in 1.3.6 but it works well in 1.3.4

**Comment by antelle** [comment]
Your archive is ok for me, could you please paste a sample code which throws an error for you?
Is it ok for you on v1.3.5?
If all else fails, I can add some logging, and we can debug it, that would be helpful.

**Comment by edtechd** [comment]
This code:

      var StreamZip = require('node-stream-zip');
      var entries = [];

			var zip = new StreamZip({  
				file: "test2.zip",
				storeEntries: true    
			});
			zip.on('error', function(error) {
					console.log('Error: ',error);
			});
			zip.on('entry', function(entry) {
				console.log('Read entry',JSON.stringify(entry));
				entries.push(entry.name);
			});
			zip.on('ready', function() {
					console.log('Entries read: ',entries);
					process.exit(0);
			});

works well on 1.3.5 and displays "Error: Bad archive" on 1.3.6

**Comment by antelle** [comment]
Hm, this works for me. Weird, something is wrong with different number of bytes read most probably.
I added some debug logging, could you please update and test it?
Please add this line before reading ZIP archive to enable logging:
```javascript
StreamZip.debug = true;
```
For me, the output is:
```
read 0 0 359 0
read 179 0 180 0
Read entry...
```

**Comment by edtechd** [comment]
read 0 0 359 0
      Error:  Bad archive

I don't know, maybe it makes sense, I use node v 0.10.31

**Comment by antelle** [comment]
Added more logging.
Expected output: 
```
read 0 0 359 0
359 0 359
358 359 358 0 80
357 359 357 0 80
356 359 356 0 80
355 359 355 0 80
354 359 354 0 80
353 359 353 179 80
352 359 352 0 80
351 359 351 0 80
350 359 350 0 80
349 359 349 158 80
348 359 348 0 80
347 359 347 2 80
346 359 346 0 80
345 359 345 2 80
344 359 344 0 80
343 359 343 0 80
342 359 342 0 80
341 359 341 0 80
340 359 340 6 80
339 359 339 5 80
338 359 338 75 80
337 359 337 80 80
read 179 0 180 0
```

**Comment by edtechd** [comment]
```
read 0 0 359 0
359 0 359
358 undefined 358 0 80
357 undefined 357 0 80
356 undefined 356 0 80
355 undefined 355 0 80
354 undefined 354 0 80
353 undefined 353 179 80
352 undefined 352 0 80
351 undefined 351 0 80
350 undefined 350 0 80
349 undefined 349 158 80
348 undefined 348 0 80
347 undefined 347 2 80
346 undefined 346 0 80
345 undefined 345 2 80
344 undefined 344 0 80
343 undefined 343 0 80
342 undefined 342 0 80
341 undefined 341 0 80
340 undefined 340 6 80
339 undefined 339 5 80
338 undefined 338 75 80
337 undefined 337 80 80
336 undefined 336 0 80
335 undefined 335 0 80
334 undefined 334 0 80
333 undefined 333 0 80
332 undefined 332 4 80
331 undefined 331 0 80
330 undefined 330 0 80
329 undefined 329 0 80
328 undefined 328 0 80
327 undefined 327 4 80
326 undefined 326 1 80
325 undefined 325 0 80
324 undefined 324 11 80
323 undefined 323 120 80
322 undefined 322 117 80
321 undefined 321 88 80
320 undefined 320 124 80
319 undefined 319 169 80
318 undefined 318 135 80
317 undefined 317 3 80
316 undefined 316 0 80
315 undefined 315 5 80
314 undefined 314 84 80
313 undefined 313 85 80
312 undefined 312 116 80
311 undefined 311 120 80
310 undefined 310 116 80
309 undefined 309 46 80
308 undefined 308 50 80
307 undefined 307 101 80
306 undefined 306 108 80
305 undefined 305 105 80
304 undefined 304 102 80
303 undefined 303 0 80
302 undefined 302 0 80
301 undefined 301 0 80
300 undefined 300 67 80
299 undefined 299 129 80
298 undefined 298 128 80
297 undefined 297 0 80
296 undefined 296 0 80
295 undefined 295 0 80
294 undefined 294 1 80
293 undefined 293 0 80
292 undefined 292 0 80
291 undefined 291 0 80
290 undefined 290 0 80
289 undefined 289 0 80
288 undefined 288 24 80
287 undefined 287 0 80
286 undefined 286 9 80
285 undefined 285 0 80
284 undefined 284 0 80
283 undefined 283 0 80
282 undefined 282 144 80
281 undefined 281 0 80
280 undefined 280 0 80
279 undefined 279 0 80
278 undefined 278 45 80
277 undefined 277 88 80
276 undefined 276 144 80
275 undefined 275 67 80
274 undefined 274 227 80
273 undefined 273 74 80
272 undefined 272 48 80
271 undefined 271 48 80
270 undefined 270 250 80
269 undefined 269 0 80
268 undefined 268 8 80
267 undefined 267 0 80
266 undefined 266 0 80
265 undefined 265 0 80
264 undefined 264 20 80
263 undefined 263 3 80
262 undefined 262 30 80
261 undefined 261 2 80
260 undefined 260 1 80
259 undefined 259 75 80
258 undefined 258 80 80
257 undefined 257 0 80
256 undefined 256 0 80
255 undefined 255 0 80
254 undefined 254 0 80
253 undefined 253 4 80
252 undefined 252 0 80
251 undefined 251 0 80
250 undefined 250 0 80
249 undefined 249 0 80
248 undefined 248 4 80
247 undefined 247 1 80
246 undefined 246 0 80
245 undefined 245 11 80
244 undefined 244 120 80
243 undefined 243 117 80
242 undefined 242 88 80
241 undefined 241 124 80
240 undefined 240 169 80
239 undefined 239 124 80
238 undefined 238 3 80
237 undefined 237 0 80
236 undefined 236 5 80
235 undefined 235 84 80
234 undefined 234 85 80
233 undefined 233 116 80
232 undefined 232 120 80
231 undefined 231 116 80
230 undefined 230 46 80
229 undefined 229 49 80
228 undefined 228 101 80
227 undefined 227 108 80
226 undefined 226 105 80
225 undefined 225 102 80
224 undefined 224 0 80
223 undefined 223 0 80
222 undefined 222 0 80
221 undefined 221 0 80
220 undefined 220 129 80
219 undefined 219 128 80
218 undefined 218 0 80
217 undefined 217 0 80
216 undefined 216 0 80
215 undefined 215 0 80
214 undefined 214 0 80
213 undefined 213 0 80
212 undefined 212 0 80
211 undefined 211 0 80
210 undefined 210 0 80
209 undefined 209 24 80
208 undefined 208 0 80
207 undefined 207 9 80
206 undefined 206 0 80
205 undefined 205 0 80
204 undefined 204 0 80
203 undefined 203 0 80
202 undefined 202 0 80
201 undefined 201 0 80
200 undefined 200 0 80
199 undefined 199 0 80
198 undefined 198 0 80
197 undefined 197 0 80
196 undefined 196 0 80
195 undefined 195 0 80
194 undefined 194 74 80
193 undefined 193 48 80
192 undefined 192 48 80
191 undefined 191 244 80
190 undefined 190 0 80
189 undefined 189 0 80
188 undefined 188 0 80
187 undefined 187 0 80
186 undefined 186 0 80
185 undefined 185 10 80
184 undefined 184 3 80
183 undefined 183 30 80
182 undefined 182 2 80
181 undefined 181 1 80
180 undefined 180 75 80
179 undefined 179 80 80
178 undefined 178 0 80
177 undefined 177 33 80
176 undefined 176 111 80
175 undefined 175 195 80
174 undefined 174 76 80
173 undefined 173 16 80
172 undefined 172 108 80
171 undefined 171 37 80
170 undefined 170 62 80
169 undefined 169 100 80
168 undefined 168 65 80
167 undefined 167 2 80
166 undefined 166 229 80
165 undefined 165 231 80
164 undefined 164 74 80
163 undefined 163 47 80
162 undefined 162 203 80
161 undefined 161 208 80
160 undefined 160 171 80
159 undefined 159 79 80
158 undefined 158 201 80
157 undefined 157 42 80
156 undefined 156 44 80
155 undefined 155 72 80
154 undefined 154 85 80
153 undefined 153 207 80
152 undefined 152 202 80
151 undefined 151 43 80
150 undefined 150 72 80
149 undefined 149 81 80
148 undefined 148 77 80
147 undefined 147 73 80
146 undefined 146 76 80
145 undefined 145 79 80
144 undefined 144 201 80
143 undefined 143 203 80
142 undefined 142 207 80
141 undefined 141 47 80
140 undefined 140 201 80
139 undefined 139 72 80
138 undefined 138 85 80
137 undefined 137 73 80
136 undefined 136 204 80
135 undefined 135 203 80
134 undefined 134 75 80
133 undefined 133 0 80
132 undefined 132 0 80
131 undefined 131 0 80
130 undefined 130 0 80
129 undefined 129 4 80
128 undefined 128 0 80
127 undefined 127 0 80
126 undefined 126 0 80
125 undefined 125 0 80
124 undefined 124 4 80
123 undefined 123 1 80
122 undefined 122 0 80
121 undefined 121 11 80
120 undefined 120 120 80
119 undefined 119 117 80
118 undefined 118 88 80
117 undefined 117 124 80
116 undefined 116 169 80
115 undefined 115 135 80
114 undefined 114 88 80
113 undefined 113 124 80
112 undefined 112 169 80
111 undefined 111 135 80
110 undefined 110 3 80
109 undefined 109 0 80
108 undefined 108 9 80
107 undefined 107 84 80
106 undefined 106 85 80
105 undefined 105 116 80
104 undefined 104 120 80
103 undefined 103 116 80
102 undefined 102 46 80
101 undefined 101 50 80
100 undefined 100 101 80
99 undefined 99 108 80
98 undefined 98 105 80
97 undefined 97 102 80
96 undefined 96 0 80
95 undefined 95 28 80
94 undefined 94 0 80
93 undefined 93 9 80
92 undefined 92 0 80
91 undefined 91 0 80
90 undefined 90 0 80
89 undefined 89 144 80
88 undefined 88 0 80
87 undefined 87 0 80
86 undefined 86 0 80
85 undefined 85 45 80
84 undefined 84 88 80
83 undefined 83 144 80
82 undefined 82 67 80
81 undefined 81 227 80
80 undefined 80 74 80
79 undefined 79 48 80
78 undefined 78 48 80
77 undefined 77 250 80
76 undefined 76 0 80
75 undefined 75 8 80
74 undefined 74 0 80
73 undefined 73 0 80
72 undefined 72 0 80
71 undefined 71 20 80
70 undefined 70 4 80
69 undefined 69 3 80
68 undefined 68 75 80
67 undefined 67 80 80
66 undefined 66 0 80
65 undefined 65 0 80
64 undefined 64 0 80
63 undefined 63 0 80
62 undefined 62 4 80
61 undefined 61 0 80
60 undefined 60 0 80
59 undefined 59 0 80
58 undefined 58 0 80
57 undefined 57 4 80
56 undefined 56 1 80
55 undefined 55 0 80
54 undefined 54 11 80
53 undefined 53 120 80
52 undefined 52 117 80
51 undefined 51 88 80
50 undefined 50 124 80
49 undefined 49 169 80
48 undefined 48 124 80
47 undefined 47 88 80
46 undefined 46 124 80
45 undefined 45 169 80
44 undefined 44 124 80
43 undefined 43 3 80
42 undefined 42 0 80
41 undefined 41 9 80
40 undefined 40 84 80
39 undefined 39 85 80
38 undefined 38 116 80
37 undefined 37 120 80
36 undefined 36 116 80
35 undefined 35 46 80
34 undefined 34 49 80
33 undefined 33 101 80
32 undefined 32 108 80
31 undefined 31 105 80
30 undefined 30 102 80
29 undefined 29 0 80
28 undefined 28 28 80
27 undefined 27 0 80
26 undefined 26 9 80
25 undefined 25 0 80
24 undefined 24 0 80
23 undefined 23 0 80
22 undefined 22 0 80
21 undefined 21 0 80
20 undefined 20 0 80
19 undefined 19 0 80
18 undefined 18 0 80
17 undefined 17 0 80
16 undefined 16 0 80
15 undefined 15 0 80
14 undefined 14 0 80
13 undefined 13 74 80
12 undefined 12 48 80
11 undefined 11 48 80
10 undefined 10 244 80
9 undefined 9 0 80
8 undefined 8 0 80
7 undefined 7 0 80
6 undefined 6 0 80
5 undefined 5 0 80
4 undefined 4 10 80
3 undefined 3 4 80
2 undefined 2 3 80
1 undefined 1 75 80
0 undefined 0 80 80
Error:  Bad archive

```

**Comment by antelle** [comment]
👍 
Yes, it's because of outdated Buffer implementation in old node.js runtimes.
Fixed, please update.

**Comment by edtechd** [comment]
Thank you! It works now. Maybe it makes sense to use `buffer.toString('ascii').length` instead of `buffer.length`

**Comment by antelle** [comment]
Why? [Buffer.length](https://nodejs.org/docs/latest-v0.10.x/api/buffer.html#buffer_buf_length) is a standard way to get the number of bytes in buffer.

**Comment by edtechd** [comment]
I agree, you're right, especially because byteLength uses buffer.length [internally](https://github.com/nodejs/node/blob/ff794498e713d5684feff44e1a7adb57ee993595/lib/buffer.js#L291)
