### ISSUE TITLE
node-stream-zip crashes when a bad file is opened

### ISSUE THREAD

**Issue by vnaganathan-conga** [antelle/node-stream-zip#71]
In general, most errors seem uncaught causing the node engine to crash. This issue is unfortunately not workaroundable. It makes us rethink about the use of node-stream-zip 

{ Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Bad archive')
    at StreamZip.emit (events.js:187:17)
    at StreamZip.emit (.../node_modules/node-stream-zip/node_stream_zip.js:607:33)
    at FsRead.readUntilFoundCallback [as callback] (..../node_modules/node-stream-zip/node_stream_zip.js:210:25)
    at FsRead.readCallback (..../node_modules/node-stream-zip/node_stream_zip.js:878:21)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:467:17) context: 'Bad archive' }
Waiting for the debugger to disconnect...

**Comment by antelle** [comment]
Hi! Could you please paste how you use the library? I see that errors work well in tests.

**Comment by antelle** [comment]
I think you're not listening to `error` event, that's why it happens. If you add something like
```js
zip.on('error', (err) => { logger.error(err) });
```
it should disappear.

**Comment by vnaganathan-conga** [comment]
Thanks @antelle, i will try your suggestion. Appreciate your quick response

**Comment by antelle** [comment]
Now there's also [async API](https://github.com/antelle/node-stream-zip#async-api) available, it's a bit easier to use and may worth trying, then you would get error handling automatically if you pur your async call in try..catch.
